# Site settings
title: 15/85
email: info@1585security.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://1585security.com" # the base hostname & protocol for your site
google_analytics: UA-97175295-1
twitter_username:
github_username:

# Build settings
markdown: 

#Pasted the below directly from the old yml

permalink: /:title/




